---
title: C28125 | Microsoft Docs
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C28125
helpviewer_keywords:
- C28125
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
caps.latest.revision: 6
author: corob-msft
ms.author: corob
manager: jillfra
ms.openlocfilehash: bd9a17d781ba106e20512aaff1c46ba0952cb9cf
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 02/15/2020
ms.locfileid: "77265758"
---
# <a name="c28125"></a>C28125
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Ostrzeżenie C28125: funkcja musi być wywołana z wewnątrz bloku try/except  
  
 Sterownik wywołuje funkcję, która musi zostać wywołana z poziomu bloku try/except, takiego jak [ProbeForRead](https://msdn.microsoft.com/library/windows/hardware/ff559876.aspx), [ProbeForWrite](https://msdn.microsoft.com/library/windows/hardware/ff559879.aspx), [MmProbeAndLockPages](https://msdn.microsoft.com/library/windows/hardware/ff554664.aspx).  
  
## <a name="example"></a>Przykład  
 Poniższy przykład kodu generuje to ostrzeżenie:  
  
```  
ProbeForRead(addr, len, 4);  
```  
  
 Poniższy przykład kodu pozwala uniknąć tego ostrzeżenia:  
  
```  
  
__try  
{  
    ProbeForRead(addr, len, 4);  
}  
__except(EXCEPTION_EXECUTE_HANDLER)  
{  
    Status = GetExceptionCode();  
    ... report error status  
}  
```
