---
title: C26111
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C26111
helpviewer_keywords:
- C26111
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 5541ec5dcc8ccd55fe5288265090e3d9c5958e04
ms.sourcegitcommit: 94b3a052fb1229c7e7f8804b09c1d403385c7630
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 04/23/2019
ms.locfileid: "62550178"
---
# <a name="c26111"></a>C26111
Ostrzeżenie C26111: Obiekt wywołujący nie zwolnił blokady \<blokada > przed wywołaniem funkcji \<func >.

 Adnotacja `_Requires_lock_not_held_` nakłada warunkiem wstępnym, czy liczba blokady dla określona blokada nie może być większa od zera, gdy wywoływana jest funkcja. Ostrzeżenie C26111 wystawiono, gdy funkcja kończy się niepowodzeniem zwolnić blokadę przed wywołaniem innej funkcji.

## <a name="example"></a>Przykład
 Poniższy przykład generuje ostrzeżenie C26111, ponieważ `_Requires_lock_not_held_` naruszenia warunku wstępnego przez wywołanie `DoNotLock` w ramach sekcji zablokowane.

```

typedef struct _DATA
{
    CRITICAL_SECTION cs;
    int d;
} DATA;

_Requires_lock_not_held_(p->cs)

void DoNotLock(DATA* p)
{
    EnterCriticalSection(&p->cs);
    p->d = 0;
    LeaveCriticalSection(&p->cs);
}

void LockedFunction(DATA* p)
{
    EnterCriticalSection(&p->cs);
    DoNotLock(p); // Warning C26111
    LeaveCriticalSection(&p->cs);
}
```