---
title: C28125
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28125
helpviewer_keywords:
- C28125
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: e66e6c3eb98fdb51c6d47c70a29240ed96a8fa04
ms.sourcegitcommit: 174c992ecdc868ecbf7d3cee654bbc2855aeb67d
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 12/06/2019
ms.locfileid: "74879142"
---
# <a name="c28125"></a>C28125
ostrzeżenie C28125: funkcja musi być wywołana z wnętrza bloku try/except

 Sterownik wywołuje funkcję, która musi zostać wywołana z poziomu bloku try/except, takiego jak [ProbeForRead](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-probeforread), [ProbeForWrite](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-probeforwrite), [MmProbeAndLockPages](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-mmprobeandlockpages).

## <a name="example"></a>Przykład
 Poniższy przykład kodu generuje to ostrzeżenie:

```cpp
ProbeForRead(addr, len, 4);
```

 Poniższy przykład kodu pozwala uniknąć tego ostrzeżenia:

```cpp
__try
{
    ProbeForRead(addr, len, 4);
}
__except(EXCEPTION_EXECUTE_HANDLER)
{
    Status = GetExceptionCode();
    ... report error status
}
```
