---
title: C6312
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 74ea9c013996ba29a3e29b724c41c3cac1e12127
ms.sourcegitcommit: e13e61ddea6032a8282abe16131d9e136a927984
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 04/26/2018
ms.locfileid: "31897062"
---
# <a name="c6312"></a>C6312
Ostrzeżenie C6312: możliwa Pętla nieskończona: Użycie stałej EXCEPTION_CONTINUE_EXECUTION w wyrażeniu filtru wyjątków try-except

 To ostrzeżenie oznacza użycie stałej `EXCEPTION_CONTINUE_EXECUTION` (lub innej przeliczanej na -1) w wyrażeniu filtru obsługi wyjątków strukturalnych. Użyj wartości stałej `EXCEPTION_CONTINUE_EXECUTION` może spowodować nieskończoną pętlę. Na przykład jeśli wyjątek został zgłoszony przez sprzęt, to instrukcji, który spowodował wyjątek zostanie ponownie. Jeśli nadal zły adres, który spowodował wyjątek, kolejny wyjątek wystąpi i obsługiwać w taki sam sposób. Powoduje to nieskończoną pętlę.

 Jawnym wywołaniem `RaiseException` będzie bezpośrednio Przyczyna nieskończoną pętlę, ale nadal będzie wykonanie kodu w bloku chronionym. Może to być nieoczekiwany i może prowadzić do nieskończonej pętli, jeśli `RaiseException` użyto w celu uniknięcia dereferencji nieprawidłowego wskaźnika.

 Zazwyczaj `EXCEPTION_CONTINUE_EXECUTION` powinny być zwracane tylko przez funkcję o nazwie w wyrażeniu filtru, który ma możliwość napraw wskaźnika, który spowodował wyjątek albo odpowiedniej pamięci.

## <a name="example"></a>Przykład
 Poniższy kod generuje ostrzeżenie:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
   *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

 Aby usunąć to ostrzeżenie, użyj następującego kodu:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```