---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: f472860cd338dee15b4005db16ba09de1e314071
ms.sourcegitcommit: 94b3a052fb1229c7e7f8804b09c1d403385c7630
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 04/23/2019
ms.locfileid: "62781898"
---
# <a name="c6318"></a>C6318
Ostrzeżenie C6318: Niewłaściwie zdefiniowane __try /\__except: Użycie stałej EXCEPTION_CONTINUE_SEARCH lub innej przeliczanej na zero w wyrażeniu filtru wyjątków. Kod w bloku obsługi wyjątków nie jest wykonywany.

 To ostrzeżenie wskazuje, że jeśli wystąpi wyjątek w bloku chronionym procedury obsługi wyjątków strukturalnych, wyjątek nie będzie obsługiwana ponieważ stała `EXCECPTION_CONTINUE_SEARCH` jest używana w wyrażeniu filtru wyjątków.

 Ten kod jest równoważne z chronionego bloku bez bloku obsługi wyjątków, ponieważ nie jest wykonywany Blok obsługi.

## <a name="example"></a>Przykład
 Poniższy kod generuje to ostrzeżenie:

```
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 Aby poprawić to ostrzeżenie, użyj następującego kodu:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>Zobacz też
 [try-except, instrukcja](/cpp/cpp/try-except-statement)