---
title: C6312
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 5a67173e7621204122a26c2b0ebe632eb01000d0
ms.sourcegitcommit: 21d667104199c2493accec20c2388cf674b195c3
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 02/08/2019
ms.locfileid: "55919368"
---
# <a name="c6312"></a>C6312
Ostrzeżenie C6312: Możliwa Pętla nieskończona: Użycie stałej EXCEPTION_CONTINUE_EXECUTION w wyrażeniu filtru wyjątków try-except

 Ostrzeżenie to wskazuje na użycie stałej `EXCEPTION_CONTINUE_EXECUTION` (lub innej przeliczanej na -1) w wyrażeniu filtru obsługi wyjątków strukturalnych. Użyj wartości stałej `EXCEPTION_CONTINUE_EXECUTION` może prowadzić do wejścia w nieskończoną pętlę. Na przykład jeśli wyjątek został zgłoszony przez sprzęt, instrukcji, który spowodował wyjątek zostanie należy ponownie uruchomić. W przypadku nadal zły adres, który spowodował wyjątek, kolejny wyjątek wystąpi i być obsługiwane w taki sam sposób. Powoduje to nieskończoną pętlę.

 Jawnym wywołaniem `RaiseException` zostanie bezpośrednio Przyczyna wejścia w nieskończoną pętlę, ale będzie wykonania kodu w bloku chronionym. Może to być nieoczekiwany i może prowadzić do pętli nieskończonej, jeżeli `RaiseException` był używany w celu uniknięcia dereferencji nieprawidłowego wskaźnika.

 Zazwyczaj `EXCEPTION_CONTINUE_EXECUTION` powinny być zwracane tylko przez funkcję o nazwie w wyrażeniu filtru, który ma szansę, aby naprawić wskaźnika, który spowodował wyjątek albo podstawowa pamięć.

## <a name="example"></a>Przykład
 Poniższy kod generuje to ostrzeżenie:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
   *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

 Aby poprawić to ostrzeżenie, użyj następującego kodu:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```